### ISSUE TITLE
The customergroup table name mentioned is wrong

### ISSUE THREAD

**Issue by vinayshah** [AdobeDocs/commerce-services#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which topic?

https://developer.adobe.com/commerce/services/graphql/catalog-service/categories/#required-headers

### What's wrong with the content?

The `customer_group_data_exporter` table mentioned in the documentation is not found when searched. The table name has changed. It should be `scopes_customergroup_data_exporter`

### What changes do you propose?

To get correct information from the documentation

### Anything else that can help to cover this?

When connecting other services it will be helpfull for new merchants

**Comment by meker12** [comment]
This issue was addressed by [PR 129](https://github.com/AdobeDocs/commerce-services/pull/129)

The customer group code for the `Magento-Customer-Group` is the encrypted value of customer group id `sha1 (<customer_group_id>`  

The documentation was updated to provide the required information, which includes the encrypted value for Adobe Commerce default customer groups.
https://developer.adobe.com/commerce/services/graphql/catalog-service/categories/#required-headers
